### PR TITLE
use random-access-storage instead of abstract-random-storage.

### PR DESCRIPTION
**Pull request by rhodey**
Yo, I found a use for your module but I had to update it to use the new random-access-storage patterns. Tested using [random-access-test](https://github.com/random-access-storage/random-access-test).

### CODE REVIEW

**Comment by rhodey** [comment]
it appears to me that the travis build is only failing because the test suite does not support early versions of Node, right?

**Comment by rhodey** [comment]
I was hoping for a small diff at first but I ran into some bugs when testing writes and reads that span multiple instances, the fix required some shuffling.

**Comment by mafintosh** [comment]
Thanks for the PR @rhodey :) Is this ready for review?

**Comment by rhodey** [comment]
hey @mafintosh glad to be involved :)

yes I have done my best to make this PR ready for review, I believe it is good. unfortunately I ran into programming burnout recently so I won't be super available if any significant adjustments are needed.

be well!

**Comment by mafintosh** [comment]
@rhodey uff burn out is tough, i'll try to get this to the finish line at some point :)

**Comment by rhodey** [comment]
I have encountered a bug in my branch where `destroy()` is called incorrectly, I am closing this until I can sort out a fix and add a test case.

**Comment by rhodey** [comment]
my mistake! this still works as expected.

**Comment by rhodey** [comment]
I just ran into this error condition inside my branch of multi-random-access which I had previously thought was not possible

https://github.com/rhodey/multi-random-access/blob/sunshine/index.js#L342

Closing this PR until I can find a fix.

**Pull request closed without merging**
